version: 2

phases:
  build:
    commands:
      - echo Entered build phase
      - mvn clean package
   post_build:
     commands:
       - echo build completed
artifacts:
  files:
    - target/order-service.jar
  discards-paths:yes   